sudo: false
language: node_js
node_js:
  - node

script:
 - npm run start_lint

os:
  - osx

deploy:
  provider: psges
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: dynamic

  
  